export const SKILLS = [
  "Accounting",
  "Administrative",
  "Analytical Thinking",
  "Artificial Intelligence",
  "Bilingual",
  "Business Development",
  "Communication",
  "Computer Programming",
  "Content Creation",
  "Copywriting",
  "Customer Service",
  "Data Analysis",
  "Data Entry",
  "Data Management",
  "Data Science",
  "Design",
  "Digital Marketing",
  "Editing",
  "Electrical Engineering",
  "Event Planning",
  "Finance",
  "Graphic Design",
  "Healthcare",
  "Human Resources",
  "Information Technology",
  "Interpersonal Skills",
  "Java Programming",
  "Leadership",
  "Machine Learning",
  "Management",
  "Market Research",
  "Marketing",
  "Mathematics",
  "Microsoft Office",
  "Negotiation",
  "Network Security",
  "Organizational Skills",
  "Photography",
  "Problem Solving",
  "Product Management",
  "Project Management",
  "Public Relations",
  "Recruiting",
  "Research",
  "Sales",
  "Search Engine Optimization (SEO)",
  "Social Media",
  "Software Development",
  "Spanish Language",
  "Strategic Planning",
  "Supply Chain Management",
  "Teaching",
  "Teamwork",
  "Time Management",
  "Troubleshooting",
  "UX/UI Design",
  "Video Editing",
  "Web Development",
  "Writing",
  "Account Manager",
  "Administrative Assistant",
  "Business Analyst",
  "Chef",
  "Civil Engineer",
  "Content Writer",
  "Customer Support Representative",
  "Data Analyst",
  "Database Administrator",
  "Digital Marketer",
  "Doctor",
  "Electrical Engineer",
  "Event Coordinator",
  "Financial Analyst",
  "Front-end Developer",
  "Graphic Designer",
  "Human Resources Manager",
  "Information Security Analyst",
  "Java Developer",
  "Lawyer",
  "Machine Learning Engineer",
  "Marketing Manager",
  "Mechanical Engineer",
  "Nurse",
  "Operations Manager",
  "Photographer",
  "Product Manager",
  "Project Manager",
  "Public Relations Specialist",
  "Recruiter",
  "Research Analyst",
  "Sales Manager",
  "Software Engineer",
  "Teacher",
  "UX/UI Designer",
  "Video Editor",
  "Web Developer",
];
